### ISSUE TITLE
Change authentication mechanism

### ISSUE THREAD

**Issue by McPatate** [huggingface/hfcc.nvim#10]
As suggested by BaggiPonte [here](https://www.reddit.com/r/neovim/comments/13buwoh/comment/jk4902n), people usually version their nvim configuration.

Current mechanism for authentication requires passing the token in the plugin configuration which can lead to unintended upload of HF tokens.

**Comment by baggiponte** [comment]
Heya! Technically uses could to this:

```lua
require("lazy").setup({
  {
    'huggingface/hfcc.nvim',
    opts = {
      api_token = os.getenv("HF_TOKEN"),
      model = "bigcode/starcoder" -- can be a model ID or an http endpoint
    }
  },
})
```

`hfcc.nvim` could either:

1. Add this to the doc as a recommendation
2. Add another `env_token`-like parameter, and make `api_token` an optional variable, to allow users to specify the name of an env var that will be fetch with `os.getenv`
3. If `api_token` is uppercase, it will be automatically interpreted as an env var to get

If HF has some default variables or config dirs, then hfcc.nvim could look by default for a token in HF config dir

**Comment by McPatate** [comment]
I went ahead and did the PR since explaining it would be as lengthy as doing it :)

Let me know what you think and I'll merge it after your review (if you'd like to review).

Thank you for your input!
