### ISSUE TITLE
Having autocompleted code conform to python spacing?

### ISSUE THREAD

**Issue by klei22** [huggingface/hfcc.nvim#14]
Currently hfcc adds newlines in python  as tabs instead of 4 spaces: 
```python
    args = parse_args()
	random = randint(0,9)
	print(random)
```
I currently fix this with running a `:retab` command after autocomplete, which works, however wondering if there might be a way to preprocess the code before it gets added to the buffer (or if there is a vim setting I can use to have it add using spaces instead of tabs?)

**Comment by McPatate** [comment]
I think this is the output of the model, it seems it also has an opinion on the tabs v spaces debate 😄 

It's odd though that the model would output tabs if you have spaces in your file 🤔

I'm wondering if it's not best to leave the prediction as is and let people reformat the suggestion. In my case, when I save a file it automatically runs my formatter so it would change the tabs into spaces automatically. I'd rather not make the plugin too opinionated in that regard, but maybe there's something simple that I'm missing here.

**Comment by McPatate** [comment]
Closing for now
