### ISSUE TITLE
Is it possible to support insert mode mapping?

### ISSUE THREAD

**Issue by nyngwang** [huggingface/hfcc.nvim#6]
As title. It seems that one can only make use of one command `:HFccSuggestion`. And this forces us to get a suggestion in normal mode. It will be more natural if we could trigger it in insert mode. Thanks!

**Comment by McPatate** [comment]
I agree! I was thinking of implementing what other similar plugins do where suggestion is triggered while typing, avoiding the need to use a command.

**Comment by klei22** [comment]
This sounds great!

At first, I was looking into making a visual mode mapping
Just pieced together a insert mode mapping.

This imap works for me for python code completion:

```vim
inoremap <c-f> <esc>:HFccSuggestion<CR>
```

Not sure what a good default mapping would be (maybe leader hf), but may be better to be really easy using the home keys if the user will be using this invocation pretty often.

**Comment by McPatate** [comment]
Just a heads up, I'm currently working on this (best effort).

I was wondering, should I keep the `HFccSuggestion` command as it is or should I remove it?

**Comment by nyngwang** [comment]
It depends on you :)

My opinion just for reference: You could: 1) keep the command so that those who are using it will not experience the break, and provide an option to opt out of the command creation. 2) Just let it break since you have clearly said in your README the project is at the WIP stage.

**Comment by McPatate** [comment]
Alright, I've just merged the work from #15, let me know what you think!

**Comment by nyngwang** [comment]
@McPatate How do I enable it by default? Insert mode suggestion, is it possible to set it via `setup`?

**Comment by McPatate** [comment]
It's enabled by default, currently not possible to turn it on/off via `setup`
